#!/usr/bin/env bash
# ==============================================================================
# ScatterID — Turnkey Setup & First-Time Provisioning
# ==============================================================================
# Run this script on initial repository setup or when performing a clean rebuild.
# It validates host tools, provisions 256-bit entropy keys in .env, compiles the
# TypeScript SDK, generates internal mTLS certs, and bootstraps the Fabric blockchain.
#
# Usage:
#   ./scripts/quickstart.sh                   # Core backend (Crypto + Gateway + Fabric + Vault)
#   ./scripts/quickstart.sh --build           # Force rebuild of container images
#
# For routine day-to-day startup, use: ./scripts/start.sh
# ==============================================================================

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
cd "$DIR"

BUILD_FLAG=""
for arg in "$@"; do
  case $arg in
    --build)
      BUILD_FLAG="--build"
      ;;
  esac
done

# Colors for terminal output
BOLD="\033[1m"
GREEN="\033[0;32m"
CYAN="\033[0;36m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
RESET="\033[0m"

echo -e "${BOLD}${CYAN}======================================================================${RESET}"
echo -e "${BOLD}${CYAN}      ScatterID — Post-Quantum Zero-Knowledge Identity Setup          ${RESET}"
echo -e "${BOLD}${CYAN}======================================================================${RESET}"
echo ""

# ------------------------------------------------------------------------------
# 1. System Pre-flight Checks
# ------------------------------------------------------------------------------
echo -e "${BOLD}[1/6] Validating host prerequisites...${RESET}"

for cmd in docker openssl curl; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo -e "${RED}[ERROR] Required tool '$cmd' is not installed or not in PATH.${RESET}"
    echo -e "Please run: ${CYAN}./scripts/check_deps.sh --install${RESET}"
    exit 1
  fi
done

if ! docker info >/dev/null 2>&1; then
  echo -e "${RED}[ERROR] Docker daemon is not running or accessible.${RESET}"
  echo -e "Please start Docker and ensure your user is in the 'docker' group."
  exit 1
fi

COMPOSE_CMD="docker compose"
if ! docker compose version >/dev/null 2>&1; then
  if command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
  else
    echo -e "${RED}[ERROR] Docker Compose (v2+) is required but not found.${RESET}"
    exit 1
  fi
fi
echo -e "  ${GREEN}✓${RESET} Docker engine & tools validated."

# ------------------------------------------------------------------------------
# 2. Automated Secrets & Environment Setup (.env)
# ------------------------------------------------------------------------------
echo -e "${BOLD}[2/6] Provisioning cryptographic environment secrets...${RESET}"

GENERATE_ENV=false
if [ ! -f .env ]; then
  echo -e "  [+] No .env found. Generating fresh cryptographic secrets..."
  GENERATE_ENV=true
elif grep -q "CHANGE_ME" .env || ! grep -q "VERIFICATION_API_KEY" .env; then
  echo -e "  [!] Missing or placeholder secrets detected in .env. Overwriting with secure random keys..."
  GENERATE_ENV=true
fi

if [ "$GENERATE_ENV" = true ]; then
  CRYPTO_KEY=$(openssl rand -hex 32)
  VERIFY_KEY=$(openssl rand -hex 32)
  GATEWAY_KEY=$(openssl rand -hex 32)
  REVOKE_KEY=$(openssl rand -hex 32)
  VAULT_RANDOM_TOKEN=$(openssl rand -hex 32)

  cat <<EOF > .env
# ScatterID Environment Configuration (Auto-Generated by quickstart.sh)
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Cryptographic API Keys & Bearer Secrets
CRYPTO_SERVICE_API_KEY=${CRYPTO_KEY}
VERIFICATION_API_KEY=${VERIFY_KEY}
GATEWAY_API_KEY=${GATEWAY_KEY}
REVOKE_API_KEY=${REVOKE_KEY}

# Microservice Endpoints
CRYPTO_SERVICE_URL=https://crypto-service:5001
VERIFICATION_API_URL=http://verification-api:3000
CRYPTO_SERVICE_HOST=crypto-service
VERIFICATION_API_HOST=verification-api

# HashiCorp Vault Dev Configuration
VAULT_ADDR=http://vault.scatterid.com:8200
VAULT_TOKEN=${VAULT_RANDOM_TOKEN}
VAULT_ROLE_ID=
VAULT_SECRET_ID=
VAULT_SECRET_PATH=scatterid/mldsa
VAULT_DEV_MODE=true

# TLS CA Certificate Trust Path
NODE_EXTRA_CA_CERTS=/app/certs/ca.crt

# Host Exposed Ports
PORT_VERIFICATION_API=3000
PORT_CRYPTO_SERVICE=5001
PORT_VAULT=8200

# Hyperledger Fabric Network Details
FABRIC_PEER_ENDPOINT=peer0.issuer.scatterid.com:7051
FABRIC_PEER_HOST_ALIAS=peer0.issuer.scatterid.com
FABRIC_CHANNEL_NAME=scatterid-channel
FABRIC_CHAINCODE_NAME=scatterproof
FABRIC_MSP_ID=IssuerMSP
EOF
  chmod 600 .env
  echo -e "  ${GREEN}✓${RESET} Fresh 256-bit entropy secrets written to .env (chmod 600)"
else
  echo -e "  ${GREEN}✓${RESET} Existing .env validated."
fi

# Load variables into current subshell
set -a
source .env
set +a

# Compile TypeScript SDK
if [ -d "sdk" ]; then
  echo -e "  [+] Compiling TypeScript SDK..."
  (cd sdk && npm install --silent && npm run build --silent) >/dev/null 2>&1 || true
  echo -e "  ${GREEN}✓${RESET} TypeScript SDK compiled."
fi

# ------------------------------------------------------------------------------
# 3. Internal Certificate Authority & TLS Setup
# ------------------------------------------------------------------------------
echo -e "${BOLD}[3/6] Verifying internal TLS Root CA & certificates...${RESET}"

if [ ! -f "components/crypto/certs/crypto-service.crt" ] || [ ! -f "components/crypto/certs/ca.crt" ]; then
  echo -e "  [+] Generating internal Root CA and service certificates..."
  bash components/crypto/certs/generate_certs.sh >/dev/null
  echo -e "  ${GREEN}✓${RESET} TLS certificates generated."
else
  echo -e "  ${GREEN}✓${RESET} Internal TLS certificates present."
fi

# ------------------------------------------------------------------------------
# 4. Bridge Network & Blockchain Topology Setup
# ------------------------------------------------------------------------------
echo -e "${BOLD}[4/6] Bootstrapping Hyperledger Fabric ledger & Vault KMS...${RESET}"

# Ensure docker network exists so compose won't fail
docker network create scatterid_net 2>/dev/null || true

# Start Fabric orderer, peers, and Vault if not running
if ! docker ps --format "{{.Names}}" | grep -q "peer0.issuer.scatterid.com"; then
  echo -e "  [+] Launching Fabric network and consensus nodes..."
  (cd components/blockchain/fabric-network && ./start.sh >/dev/null)
  echo -e "  ${GREEN}✓${RESET} Hyperledger Fabric ledger active."
else
  echo -e "  ${GREEN}✓${RESET} Hyperledger Fabric network already running."
fi

# Configure Vault AppRole & Policies
echo -e "  [+] Synchronizing Vault KMS AppRole authentication..."
for i in {1..15}; do
  if docker exec vault.scatterid.com vault status -address=http://127.0.0.1:8200 >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" vault.scatterid.com vault auth enable approle 2>/dev/null || true
docker exec -i -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" vault.scatterid.com vault policy write issuer-policy - < components/crypto/crypto-service/vault/policies/issuer-policy.hcl >/dev/null 2>&1 || true
docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" vault.scatterid.com vault write auth/approle/role/issuer-role token_policies="issuer-policy" token_ttl=1h token_max_ttl=4h >/dev/null 2>&1 || true

export VAULT_ROLE_ID=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" vault.scatterid.com vault read -field=role_id auth/approle/role/issuer-role/role-id 2>/dev/null || echo "")
export VAULT_SECRET_ID=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" vault.scatterid.com vault write -f -field=secret_id auth/approle/role/issuer-role/secret-id 2>/dev/null || echo "")

# ------------------------------------------------------------------------------
# 5. Launch Containerized Microservices
# ------------------------------------------------------------------------------
echo -e "${BOLD}[5/6] Starting ScatterID microservices...${RESET}"

$COMPOSE_CMD up -d $BUILD_FLAG

# Bridge network connectivity between Fabric and compose stack
NET_NAME=$(docker network ls --format "{{.Name}}" | grep "scatterid_net" | head -n 1)
if [ -n "$NET_NAME" ]; then
  docker network connect "$NET_NAME" orderer.scatterid.com 2>/dev/null || true
  docker network connect "$NET_NAME" peer0.issuer.scatterid.com 2>/dev/null || true
  docker network connect "$NET_NAME" peer0.verifier.scatterid.com 2>/dev/null || true
fi

# ------------------------------------------------------------------------------
# 6. Readiness Probes & Verification
# ------------------------------------------------------------------------------
echo -e "${BOLD}[6/6] Polling service health endpoints...${RESET}"

wait_for_health() {
  local name="$1"
  local url="$2"
  local insecure="$3"
  local max_attempts=20
  local attempt=1

  while [ $attempt -le $max_attempts ]; do
    local code
    if [ "$insecure" == "true" ]; then
      code=$(curl -s -k -o /dev/null -w "%{http_code}" "$url" || echo "000")
    else
      code=$(curl -s -o /dev/null -w "%{http_code}" "$url" || echo "000")
    fi

    if [ "$code" == "200" ]; then
      echo -e "  ${GREEN}✓${RESET} $name is healthy ($url)"
      return 0
    fi
    sleep 1
    attempt=$((attempt + 1))
  done

  echo -e "  ${YELLOW}!${RESET} $name returned HTTP $code (still initializing)"
  return 0
}

wait_for_health "Crypto Service"  "https://localhost:5001/healthz" "true"
wait_for_health "Verification API" "http://localhost:3000/healthz"  "false"
echo ""
echo -e "${BOLD}${GREEN}======================================================================${RESET}"
echo -e "${BOLD}${GREEN}   ScatterID Post-Quantum Stack is Ready & Operational!               ${RESET}"
echo -e "${BOLD}${GREEN}======================================================================${RESET}"
echo ""
echo -e "  ${BOLD}Active Endpoints:${RESET}"
echo -e "    - Verification Gateway:   ${CYAN}http://localhost:3000${RESET}"
echo -e "    - Crypto Microservice:    ${CYAN}https://localhost:5001${RESET} (ML-DSA-65 / Vault)"
echo -e "    - HashiCorp Vault:        ${CYAN}http://localhost:8200${RESET}"
echo ""
echo -e "  ${BOLD}Try Issuing a Post-Quantum Credential Right Now:${RESET}"
echo -e "  ${YELLOW}curl -s -X POST http://localhost:3000/issue \\"
echo -e "    -H \"Authorization: Bearer $VERIFICATION_API_KEY\" \\"
echo -e "    -H \"Content-Type: application/json\" \\"
echo -e "    -d '{\"dataHash\":\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\"}' | jq .${RESET}"
echo ""
echo -e "  ${BOLD}Run Full Test Suite:${RESET}"
echo -e "    ${CYAN}./scripts/test_all.sh${RESET}"
echo ""
echo -e "${BOLD}${CYAN}======================================================================${RESET}"
